Improve view session logic
liquidvotingio/decidim-liquidvoting pull request #19
Opened 2020-11-05 13:10 UTC by jinjagit

Continuing work on #9

2020-11-05 13:46 UTC, jinjagit commented
Reviewers, please note: I just removed a debug comment, as it was somewhat misleading. Thanks.

2020-11-05 15:54 UTC, davefrey requested changes
Okay, I'm finding this too hard to scan, I propose a few things. 
First extract the delegation filtering logic to another method in `client.rb`, like
```ruby 
      # return exactly one delegation from delegator_email for proposal_url, or nil
      def self.delegation_for(delegator_email, proposal_url)
        # this is a hack until we can properly query a subset of delegations
        delegations = self.delegations().
          select {|d| d.delegator.email == delegator_email && d.proposal_url == proposal_url}.
          first   # returns nil if list is empty
      end 
```
We could extract to a helper or something else, but for now let's stick to two places, the client and the view.

Second, in this view, separate the lazy-init of `session` from the conditional rendering, like this:
```
if current_user
  <!-- a blank session[:delegated_to] means we haven't checked yet;
       let's make it explicitly the delegate email OR "none" -->
  if session[:delegated_to].blank?
    d = Decidim::Liquidvoting::Client.delegation_for(email: current_user.email, proposal_url: proposal_url(proposal))
    session[:delegated_to] = delegation.present? ? d.delegate.email : "none"
  end

  if session[:delegated_to] == "none" 
    ...
  else
    ...
  end
end
```
Finally, negations in conditional logic add some cognitive load; I think it's helpful when possible to avoid negation either by restructuring the code and/or using helpers like `blank?` or `present?` :-D

2020-11-05 15:56 UTC, davefrey commented
Also this delegations filtering is a hack that won't scale. If the current api doesn't allow us to give parameters like `delegator_email` and `proposal_url` in our graphql queries, we need to add that! (in another issue)

2020-11-05 16:11 UTC, jinjagit commented
> Also this delegations filtering is a hack that won't scale. If the current api doesn't allow us to give parameters like `delegator_email` and `proposal_url` in our graphql queries, we need to add that! (in another issue)
  
Agree. See my initial comment in this PR. Main issue here is prioritizing when to do this.

2020-11-06 13:00 UTC, jinjagit commented
I have accepted and included all of @davefrey's suggested changes.  
  
I have also created issue [#163](https://github.com/liquidvotingio/api/issues/163) to address the need for a specific absinthe query to facilitate the delegations filtering mentioned in preceding comments.

2020-11-06 14:10 UTC, oliverbarnes requested changes
Looking great, just a few small change requests

2020-11-06 14:10 UTC, oliverbarnes commented on lib/decidim/liquidvoting/client.rb
> +      query {
Just need to indent the query statement two spaces more, to be consistent with the mutations

2020-11-06 14:10 UTC, oliverbarnes commented on lib/decidim/liquidvoting/client.rb
> +      response = send_query(DelegationsQuery)
method block code needs to be indented further

(which reminds me we should turn on linting on the CI, I'll open an issue for it)

2020-11-06 14:10 UTC, oliverbarnes commented on lib/decidim/liquidvoting/client.rb
> +        # this is a hack until we can properly query a subset of delegations
👌

2020-11-06 14:10 UTC, oliverbarnes commented on app/controllers/decidim/liquidvoting/delegations_controller.rb
>  end
We're missing a newline here. Another linting violation to be caught by the CI

2020-11-06 14:15 UTC, oliverbarnes commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +    Support delegated to <%= Decidim::User.find_by(email: session[:delegated_to]).name %>
hmm, come to think of it, this might not be possible because the delegations controller won't have been hit yet on some scenarios

2020-11-06 14:29 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +    <% session[:delegated_to] = d.present? ? d.delegate.email : "none" %>
Agree. I was following an earlier approach of 'develop in view and then think about what goes where'. I guess now is time to decide 'where' ;-)

2020-11-06 14:30 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to] == "none" %>
So just   `<% if session[:delegated_to]? %>` ?

2020-11-06 14:34 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +    Support delegated to <%= Decidim::User.find_by(email: session[:delegated_to]).name %>
Yes, I am still not clear about when controllers get hit in `decidim-liquidvoting`, since we are looking at view rendered from decidim-instance interactions (I think), which then hit our api. So some things go via `client.rb`. Layers within layers. I am sure it will become clearer the more I work with the code.

2020-11-06 14:41 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +    Support delegated to <%= Decidim::User.find_by(email: session[:delegated_to]).name %>
> hmm, come to think of it, this might not be possible

So I'll leave this as is for now.

2020-11-06 14:56 UTC, jinjagit commented on app/controllers/decidim/liquidvoting/delegations_controller.rb
>  end
I'm assuming you mean EOF newline.

2020-11-06 15:04 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to] == "none" %>
So, this seems to break without `blank?`  
```<% if session[:delegated_to] %>
    <% d = Decidim::Liquidvoting::Client.delegation_for(current_user.email, proposal_url(proposal)) %>
    <% session[:delegated_to] = d.present? ? d.delegate.email : "none" %>
  <% end -%>
```
=>
```
undefined method `name' for nil:NilClass
Extracted source (around line #23):
21   </form>
22  <% else -%>
23    Support delegated to <%= Decidim::User.find_by(email: session[:delegated_to]).name %>
```

2020-11-06 15:07 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to] == "none" %>
I think, therefore, the view does need to know if it has been checked for, hence we introduced the idea of setting it to "none" (which was the initial motivation for this PR).

2020-11-06 15:11 UTC, oliverbarnes commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +    <% session[:delegated_to] = d.present? ? d.delegate.email : "none" %>
aka the hacky approach 😄 yeah, I was too. but time for us to start being neat

2020-11-06 15:20 UTC, oliverbarnes commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to] == "none" %>
Just use `blank?`, that's the idiomatic rails way.

But I am starting to grasp the scenario you're trying to fix with `Decidim::Liquidvoting::Client.delegation_for`, which is of a new login (clean session) after a delegation has already been given earlier. The delegations controller hasn't been hit yet, so no way to set the controller before hand there.

Unless we override the proposals vote controller too... Need to think about this, it's really not an easy thing to fix.

I'd say let's stick with the view logic for now, just not using "none" please. So simply:

```rails
<% session[:delegated_to] = d.delegate.email if d.present? %>
```

And then checking for `blank?`. Or inverting the logic, like Dave suggested, and checking for `present?` first

2020-11-06 15:21 UTC, oliverbarnes commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +    Support delegated to <%= Decidim::User.find_by(email: session[:delegated_to]).name %>
yeah :) btw, to see what gets hit, the logs will show the controllers executed

2020-11-06 15:22 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +    Support delegated to <%= Decidim::User.find_by(email: session[:delegated_to]).name %>
Logs = good idea :-)

2020-11-06 15:24 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to] == "none" %>
Ahh, I now understand. We can do this without needing to set to 'none'. Got it :+1:

2020-11-06 15:29 UTC, oliverbarnes commented on app/controllers/decidim/liquidvoting/delegations_controller.rb
>  end
<img width="231" alt="Screen Shot 2020-11-06 at 3 28 37 PM" src="https://user-images.githubusercontent.com/21290/98383736-c3d03800-2044-11eb-9a12-b379bf9dbbd6.png">

Always good to have a look at the "files changed" view on your own PRs to catch these.

2020-11-06 15:33 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to] == "none" %>
This seems to work nicely...  
```
<% d = Decidim::Liquidvoting::Client.delegation_for(current_user.email, proposal_url(proposal)) %>
  <% session[:delegated_to] = d.delegate.email unless d.nil? %>

  <% if session[:delegated_to].blank? %>
...
```

2020-11-06 15:40 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to] == "none" %>
But this would avoid hitting db unnecessarily (when `delegated_to` is correctly set):  
```
<% if session[:delegated_to].blank? %>
  <% d = Decidim::Liquidvoting::Client.delegation_for(current_user.email, proposal_url(proposal)) %>
  <% session[:delegated_to] = d.delegate.email unless d.nil? %>
<% end -%>

<% if session[:delegated_to].blank? %>
...

2020-11-06 15:42 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to] == "none" %>
Checking for a delegation every time view is rendered seems more robust, but involves a db search. Which is preferred?

2020-11-06 15:53 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +    <% session[:delegated_to] = d.present? ? d.delegate.email : "none" %>
So, are we shelving the idea of moving this to the controller, due to the same thinking as in your [_But I am starting to grasp the scenario..._](https://github.com/liquidvotingio/decidim-liquidvoting/pull/19#discussion_r518820316) comment?

2020-11-06 16:11 UTC, jinjagit commented
### Summary of progress:  
  
I think I have satisfied all suggested changes, except regarding my 2 remaining doubts:
- [Do we still wish to move more logic to the controller, or are we shelving this idea for now?](https://github.com/liquidvotingio/decidim-liquidvoting/pull/19#discussion_r518841226)  
- [Do we want the (more robust) option of checking for a delegation every time the view is rendered (which is the current PR code state)?](https://github.com/liquidvotingio/decidim-liquidvoting/pull/19#discussion_r518834431)

2020-11-06 16:46 UTC, oliverbarnes commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to] == "none" %>
yeah, let's avoid hitting the db unnecessarily

2020-11-06 16:47 UTC, oliverbarnes commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +    <% session[:delegated_to] = d.present? ? d.delegate.email : "none" %>
Yes

2020-11-06 16:57 UTC, oliverbarnes commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to].blank? %>
let's invert the logic here like Dave had suggested, please. As in, check for `present?` and if true, show the second block first

2020-11-06 16:58 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to].blank? %>
I'm confused as I think it is inverted as Dave suggested.

2020-11-06 16:58 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to].blank? %>
But I can re-invert the inversion.

2020-11-06 17:02 UTC, jinjagit commented on app/views/decidim/proposals/proposals/_vote_button.html.erb
> +  <% if session[:delegated_to].blank? %>
...and done.

2020-11-06 17:03 UTC, oliverbarnes approved these changes

2020-11-06 17:06 UTC, merged